### ISSUE TITLE
Support ClassPortal routes for AutoTest

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/sdmm-portal-backend#11]
```
isStaff(courseId: string, userName: string): Promise<boolean>

getDefaultDeliverableId(commitUrl: string): Promise<string | null> 

getContainerDetails(courseId: string, delivId: string): Promise<{ dockerImage: string, dockerBuild: string, testDelay: number, regressionDelivNames: string[] } | null> 
```
@nickbradley what fields do you need that are returned by the bottom query?

**Comment by ncbradley** [comment]
- `dockerImage`: secapstone-grader
- ~`dockerBuild`~
- `testDelay` -> `callRateLimit`: any value
- add `maxContainerExecTime` or `maxWorkerExecTime` or `maxExecTime`: 300

**Comment by rtholmes** [comment]
`callRateLimit` -> `studentDelay` 
`maxExecTime` for the other
